### ISSUE TITLE
cloudflares https://1.1.1.1/cdn-cgi/trace and https://1.0.0.1/cdn-cgi/trace are not returning the client ip anymore

### ISSUE THREAD

**Issue by cchriso** [timothymiller/cloudflare-ddns#216]
**Describe the bug**
I noticed my ddns updates are updated with a weird ip address and I had a look at the code - I saw that the cloudflare /cdn-cgi/trace endpoint are giving back a strange IP (104.18.0.0) and not my client ip as usual, so we have to find another way to get the current ip. I found that [https://cloudflare.com/cdn-cgi/trace](https://cloudflare.com/cdn-cgi/trace) is still serving the correct client IP, I will submit a PR that fixes this probably today.
I was not able to find docs regarding a change to that endpoint from cloudflare. So maybe it is a fluke/hiccup and cloudflare will fix it

**To Reproduce**
1. Go to [https://1.1.1.1/cdn-cgi/trace](https://1.1.1.1/cdn-cgi/trace) and see the ip for yourself

**Expected behavior**
that it returns the client ip

**Screenshot**

<img width="305" height="314" alt="Image" src="https://github.com/user-attachments/assets/96b8a94e-ecf3-44ce-ba64-73022d23f14f" />

<img width="329" height="300" alt="Image" src="https://github.com/user-attachments/assets/7898ad19-1706-4e83-9006-cfaf744e19a4" />

**Additional context**
I understand that this is a cloudflare issue, nonetheless the application is not working

**Comment by PhaineDev** [comment]
Same issue here. Everything pointing to: 104.18.0.0

**Comment by darioackermann** [comment]
10$ side bet new cloudflare interns forgot to forward the original clients' IP when changing some ingress balancer config 😂

**Comment by dankmeme01** [comment]
Ran into this as well, as far as I know the `cdn-cgi/trace` endpoint is meant for debugging only and Cloudflare does not make any guarantees about what it returns. Would be more sensible to not rely on it at all

I've personally used https://api.ident.me, it's simple and privacy friendly

**Comment by darioackermann** [comment]
basically this one https://github.com/timothymiller/cloudflare-ddns/pull/203 with some variety of `ifconfig.co`, `api.ipify.org` , etc...

**Comment by GreepTheSheep** [comment]
+1

IPv4 gives 104.18.0.0
IPv6 gives 2606:4700:7::

**Comment by Javinator9889** [comment]
Just happened to me right now, lost all connections!

Is this addressed on a newer version? Or can I configure the endpoint to return the IP?

I personally love api.ipify.com and api64.ipify.com

**Comment by nicholas-karr** [comment]
Cloudflare already fixed it for me as of a minute ago. It was returning the same IP as you for about half an hour.

**Comment by Tarballwalf** [comment]
Can confirm. I was freaking out thinking I got blacklisted somehow

**Comment by cchriso** [comment]
True, now cloudflare fixed it. But nonetheless I think I will fork this repo and push my own docker images just to be sure in the future, I really want to be able to control where it gets my IP from and I think this repo in general is rather dead...

**Comment by Tarballwalf** [comment]
damn I was not even aware this project is basically _dead_. I've set this up years ago and it had just worked fine ¯\_(ツ)_/¯

**Comment by allancoding** [comment]
Same thing append to me. I lost access to everything. Randomly fixed a couple minutes ago.

**Comment by cchriso** [comment]
if the issue happens again you can use my image on dockerhub [https://hub.docker.com/r/cchriso/cloudflare-ddns](https://hub.docker.com/r/cchriso/cloudflare-ddns) - here I resolve the IPs with the [https://cloudflare.com/cdn-cgi/trace](https://cloudflare.com/cdn-cgi/trace) url, which worked when the issue arised with the IPs directly

I also will continue to work on the fork, so feel free to open new issues with suggestions. I for sure want to enable more IP resolvers like api.myip.com etc.
Link to my fork: [https://github.com/cchriso/cloudflare-ddns](https://github.com/cchriso/cloudflare-ddns)

**Comment by cchriso** [comment]
pushed a new release in my fork - version [2.0.0](https://github.com/cchriso/cloudflare-ddns/releases/tag/2.0.0)
[https://github.com/cchriso/cloudflare-ddns](https://github.com/cchriso/cloudflare-ddns)

We are now able to use 3 other IP resolution services 🥳 
* myip.com
* ifconfig.co
* ident.me

https://github.com/cchriso/cloudflare-ddns?tab=readme-ov-file#-ip-detection-vendors

**Comment by allancoding** [comment]
> pushed a new release in my fork - version [2.0.0](https://github.com/cchriso/cloudflare-ddns/releases/tag/2.0.0) [cchriso/cloudflare-ddns](https://github.com/cchriso/cloudflare-ddns)
> 
> We are now able to use 3 other IP resolution services 🥳
> 
> * myip.com
> * ifconfig.co
> * ident.me
> 
> [cchriso/cloudflare-ddns#-ip-detection-vendors](https://github.com/cchriso/cloudflare-ddns?tab=readme-ov-file#-ip-detection-vendors)

I was wondering if it could check multiple servers to make sure its the correct ip, before updating the address. Mainly so this won't ever happen again.

**Comment by oberwager** [comment]
After this went happened I looked into the code a bit more. I decided to rewrite it entirely in Golang over the weekend, and added a few more improvements to the Docker container. 

Notably:
- Now it doesn't have to run 24/7, can schedule it like a cronjob
- 6MB binary size
- Concurrency for updating zones and records for massive speed up
- Structured logging for better visibility
- Uses apify to get IP, still no log and better reliability (its actually documented, unlike cdn/cgi/trace)
- Exponential backoff to retry getting IP
- Docker image doesn't run as root

Check it out at https://github.com/oberwager/cloudflare-ddns and let me know your feedback.

**Comment by orpheus1120** [comment]
> pushed a new release in my fork - version [2.0.0](https://github.com/cchriso/cloudflare-ddns/releases/tag/2.0.0) https://github.com/cchriso/cloudflare-ddns
> 
> We are now able to use 3 other IP resolution services 🥳
> 
> * myip.com
> * ifconfig.co
> * ident.me
> 
> https://github.com/cchriso/cloudflare-ddns?tab=readme-ov-file#-ip-detection-vendors

You should also add icanhazip.com as one of the IP resolution service. It's one of the most popular ones.

if you have not heard about it before, read more over here: https://major.io/p/a-new-future-for-icanhazip/

**Comment by KhooHaoYit** [comment]
I encountered this issue today
I have used this patch https://github.com/timothymiller/cloudflare-ddns/pull/203 and reversed the order of endpoints which should prefer fetching ip from icanhazip.com instead of cloudflare to decrease the chance of it happening again

**Comment by orpheus1120** [comment]
@KhooHaoYit I had a look at the PR you quoted. However the PR uses `https://1.1.1.1/cdn-cgi/trace` as the primary IP source and failback to `icanhazip.com`. As we know both 1.1.1.1 and 1.0.0.1 still fail to fetch the correct IP, only fetching `104.18..0.0` as noted by OP in this current issue.  Since the primary `1.1.1.1` endpoint technically fetches an IP albeit the wrong one, the fallback `icanhazip` endpoint was never used. I ran the image and verified.

I guess the issue of `1.1.1.1` failing to retrieve the correct IP didn't manifest at the time of the PR.

So unfortunately that patch doesn't solve the issue.

I think it's best to ditch Cloudflare's endpoints entirely and only use `icanhazip` as primary. A fallback endpoint of another provider can also be helpful, which was what you ended up doing.

**Comment by KhooHaoYit** [comment]
@orpheus1120 I think you have misunderstood me

The PR is in no way, shape and form, fix this issue since it still uses cloudflare to resolve it's external ip

I have posted that comment with the intention of informing others that it could be **TEMPORARY** fixed by preferring to use icanhazip.com resolver in order to reduce the usage of cloudflare resolver that might return `104.18.0.0` which is what I have done

**Comment by irfanhakim-as** [comment]
Surprised to see that my old PR is still getting some attention haha - I'm sure a lot of people's implemented their own fix by now, but thought I'd mention that I've just merged a fix on my fork: https://github.com/irfanhakim-as/cloudflare-ddns/pull/3 ([Docker image](https://github.com/irfanhakim-as/cloudflare-ddns/pkgs/container/cloudflare-ddns/717156745?tag=1.0.3-master-r1)), in case anyone needs it.

**Comment by orpheus1120** [comment]
Ok, I see you are using a voting system. 👍 Might want to update your `readme.md` to include the correct image in the `docker compose` section.

**Comment by eric2788** [comment]
+1, I have switched to https://github.com/favonia/cloudflare-ddns

**Comment by orpheus1120** [comment]
That's a nice repo and that's what I'm currently using. I hope the author gets well soon.

**Comment by fqfqgo** [comment]
I did a fork, and fix it. just replace  [cloudflare-ddns.py](https://github.com/fqfqgo/cloudflare-ddns/blob/master/cloudflare-ddns.py)  will fix it.
https://github.com/fqfqgo/cloudflare-ddns

**Comment by masterwishx** [comment]
> I did a fork, and fix it. just replace [cloudflare-ddns.py](https://github.com/fqfqgo/cloudflare-ddns/blob/master/cloudflare-ddns.py) will fix it. https://github.com/fqfqgo/cloudflare-ddns

How to use in docker?

**Comment by masterwishx** [comment]
> pushed a new release in my fork - version [2.0.0](https://github.com/cchriso/cloudflare-ddns/releases/tag/2.0.0) https://github.com/cchriso/cloudflare-ddns
> 
> We are now able to use 3 other IP resolution services 🥳
> 
> * myip.com
> * ifconfig.co
> * ident.me
> 
> https://github.com/cchriso/cloudflare-ddns?tab=readme-ov-file#-ip-detection-vendors

updated to your forked version but still had issue ,but after 5min got IP , interesting that found this issue ONLY today used this original project !!!

**Comment by masterwishx** [comment]
> > pushed a new release in my fork - version [2.0.0](https://github.com/cchriso/cloudflare-ddns/releases/tag/2.0.0) https://github.com/cchriso/cloudflare-ddns
> > We are now able to use 3 other IP resolution services 🥳
> > 
> > * myip.com
> > * ifconfig.co
> > * ident.me
> > 
> > https://github.com/cchriso/cloudflare-ddns?tab=readme-ov-file#-ip-detection-vendors
> 
> updated to your forked version but still had issue ,but after 5min got IP , interesting that found this issue ONLY today used this original project !!!

Seems working with `Detected Cloudflare proxy IP, trying cloudflare.com instead`...

**Comment by masterwishx** [comment]
> Surprised to see that my old PR is still getting some attention haha - I'm sure a lot of people's implemented their own fix by now, but thought I'd mention that I've just merged a fix on my fork: [irfanhakim-as#3](https://github.com/irfanhakim-as/cloudflare-ddns/pull/3) ([Docker image](https://github.com/irfanhakim-as/cloudflare-ddns/pkgs/container/cloudflare-ddns/717156745?tag=1.0.3-master-r1)), in case anyone needs it.

For me not worked with : 
```print("⚠️ %s endpoint disagreement detected: %s" % (label, {ip: hosts for ip, hosts in votes.items()}))```

**Comment by JtMotoX** [comment]
This issue has been open for 5 months and still not fixed. It looks like the maintainer of this project closed this issue without fixing it. I am assuming that means this project is dead.

> +1, I have switched to https://github.com/favonia/cloudflare-ddns

Thanks @eric2788 for sharing this alternative. It took me about 10 minutes to switch over to https://github.com/favonia/cloudflare-ddns. I am up-and-running again.

**Comment by dimpen** [comment]
I created **[cloudflare-ddns-next](https://github.com/dimpen/cloudflare-ddns-next)** 
It includes ideas and fixes from the pull requests and adds **many new features and services**.
It's geared towards system administrators for security, reliability and easy debugging.
It also has a **new consensus algorithm** to obtain IPs.
Check it out!

**Comment by teo0781** [comment]
> This issue has been open for 5 months and still not fixed. It looks like the maintainer of this project closed this issue without fixing it. I am assuming that means this project is dead.

The project is now sh*tcode written mostly by ai.
11k lines of rust to replace a 390 or so line pytohn script.

I sure as hell know that I'm not using this project anymore.

**Comment by dimpen** [comment]
> > This issue has been open for 5 months and still not fixed. It looks like the maintainer of this project closed this issue without fixing it. I am assuming that means this project is dead.
> 
> The project is now sh*tcode written mostly by ai. 11k lines of rust to replace a 390 or so line pytohn script.
> 
> I sure as hell know that I'm not using this project anymore.

My project, on the other hand, is completely handwritten with the minimal required code to efficiently implement all the the features.

I've kept it on **python** that's more common and the implementation is hardened and focused on **easy debugging** with **robust logging and error messages**.

I've also made it very easy to add new services if you want to contribute.

Check it out! 🙂

**https://github.com/dimpen/cloudflare-ddns-next**


## ✨ New Features

- 🛡️ **NEW Hardened Consensus Algorithm**: Queries multiple IP services; updates only if the majority agree. (or stick with the old "priority" algorithm)
- 🔍 **Smart Logging**: JSON (or text) logs, rotation, timestamps, and separate IP history logs.
- 🔄 **Multi-Account**: Manage multiple Cloudflare accounts and zones in one place.
- 📝 **JSON5 Config**: Add comments (`//`,`/* */`) to your configuration file.
- 💓 **BetterStack Integration**: Native integration for heartbeat monitoring and alerts.
- **Blacklist** IPs ([issue 216](https://github.com/timothymiller/cloudflare-ddns/issues/216))
- **A/AAAA** mixed type of records and **TTL/proxied** set **per subdomain**
- Increased **security**, **performance** and easier **debugging**
- Run **external script on error** to take action or notify
- **Config validation** (`jsonschema`), minimizing errors 
- **Timestamped or custom comment** in Cloudflare DNS records
- Increased **error checking** and **exception handling**. *If one fails the rest go on*
- ⚡ **Modern Core**: Upgraded to **Python 3.10+** and `Session` requests for performance and security.
- 🐳 **Docker Ready**
- **More services for obtaining IP** and even more to come
- **Supported Services: ["1.1.1.1", "1.0.0.1", "cloudflare.com", "ipify", "icanhazip", "identme", "ifconfigco", "myipcom"]**

**Comment by orpheus1120** [comment]
No heartbeat monitors like uptime-kuma or healthchecks. No notification like pushover, discord, slack etc. I've never heard of BetterStack so I don't know its privacy policy. Been using pushover for over 10 years and a uptime-kuma user. Also console output is not detailed enough. 

External script implementation is nice but should be complementary to uptime/kuma/healthchecks. I've no problem with your other features.

**Comment by dimpen** [comment]
> No heartbeat monitors like uptime-kuma or healthchecks. No notification like pushover, discord, slack etc. I've never heard of BetterStack so I don't know its privacy policy. Been using pushover for over 10 years and a uptime-kuma user. Also console output is not detailed enough.
> 
> External script implementation is nice but should be complementary to uptime/kuma/healthchecks. I've no problem with your other features.

@orpheus1120 

Thanks for your input! 👍

1. I'll be adding **uptime kuma** and **docker healthchecks**.
  
2. I'm planning to integrate **Apprise**. Apprise covers all the notifications you mentioned and more.
    - I want to keep the codebase simple and clean. Adding all these notifications separately would create unnecessary complexity.
    - Currently my personal external script is a very simple script that sends an email and an apprise notification.
    - Betterstack is a relatively new heartbeat and monitor service. As a sys/cybersecurity admin, I don't trust anyone's privacy policy. It was just an easy service to integrate.
3. **The logs are very extensive and detailed** which is the main focus of my implementation. Logs that can immediately pinpoint the issue in case of an error.
    - There are levels that you can set independently (stdout or logfile): ["CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"]. (text or json)
    - The error logs provide the runtime python error. Everything is in **try/catch** and all **Exceptions are handled and logged**.
4. I cover all the **configuration options** in detail in the [Configuration-Wiki](https://github.com/dimpen/cloudflare-ddns-next/wiki).
  
---

Anyway my repo is new and I'm sure it lacks many features others would want.

Currently I've implemented the features I require and I have a **roadmap of more upcoming features**.

**The point of announcing my project here is to get more people involved so we can implement more features and make the project more robust for the community.**

There are other projects that have poped up since this issue and repos that have been up for years, that didn't meet my needs. They're either too simple lacking features or too complex with a huge codebase.

I've also kept the code on **Python** so it's a smoother DX for devs that are familiar with this project.

Let's not pollute this issue any more about this. 
Hopefully you care enough to get involved and open issues or PRs on my [repo](https://github.com/dimpen/cloudflare-ddns-next) for any features you want. 

Even if you can't use it now because it lacks a feature you require, you can **open a feature request so you are notified when it is implemented**.

**I'm actively maintaining the repo and I welcome any issues, feature requests, PRs and contributions!** 🙂

**Comment by luisg123v** [comment]
The endpoint is still failing for me today. I noticed consuming it sometimes works, depending on where is consumed from.

Since the issue is reproduced only when accessing the IP directly but it works when using the host name (one.one.one.one), I've solved this same issue in a project I use for myself by passing the domain in the headers: https://github.com/luisg123v/cloudflare-dns-updater/pull/1

Headers:

    Host: one.one.one.one

That makes the request to behave as if the domain were provided, but without actually doing a DNS query, which was the reason for me to use this specific service instead of other aternatives like ipify.

**Comment by dimpen** [comment]
> The endpoint is still failing for me today. I noticed consuming it sometimes works, depending on where is consumed from.
> 
> Since the issue is reproduced only when accessing the IP directly but it works when using the host name (one.one.one.one), I've solved this same issue in a project I use for myself by passing the domain in the headers: [luisg123v/cloudflare-dns-updater#1](https://github.com/luisg123v/cloudflare-dns-updater/pull/1)
> 
> Headers:
> 
> ```
> Host: one.one.one.one
> ```
> 
> That makes the request to behave as if the domain were provided, but without actually doing a DNS query, which was the reason for me to use this specific service instead of other aternatives like ipify.

**Nice catch** @luisg123v 👍

This fix also works for `1.0.0.1` with the same `Host: one.one.one.one`

I've already patched my project too.
Thanks for posting this!
